### ISSUE TITLE
No way to set allowHttp = true for horizon server

### ISSUE THREAD

**Issue by sgehrman** [stellar/bifrost-js-sdk#4]
Let me know if I missed something, but can't set allowHttp=true in this SDK.  I'll just change my copy of the code.

**Comment by lshiffer** [comment]
Same...

Added 'horizonAllowHttp: true' to my params but as soon as a new Bifrost.Session happens get a 'Uncaught Error: Cannot connect to insecure horizon server'

**Comment by bartekn** [comment]
It's updated in an unreleased code. If you need it you should build the JS SDK yourself by using `gulp build`.
